name: Iris
source: "."
dest: "build"
ignore:
  - .git/*
  - build/*
  - .deploy/*
  - generate.py
  - pip-selfcheck.json
  - bin
  - lib
  - include
  - requirements.txt
  - README.md
  - LICENSE
  - examples